export default {
  security: {
    title: 'Security Settings',
    subtitle: 'Manage your account security and authentication.',
    password: 'Password',
    lastChanged: 'Last changed {timeSince}',
    neverChanged: 'Never updated',
    changePasswordButton: 'Change Password',
    totp: 'Two-Factor Authentication',
    totpSubtitle: 'Add an extra layer of security to your account',
    totpEnabled: 'Enabled',
    totpDisabled: 'Disabled',
    totpConfigureButton: 'Configure',
    passwordVerifyForm: {
      title: 'Verify your password',
      subtitle: 'Confirm password to setup 2FA',
      label: 'Password',
      button: 'Verify',
      validation: {
        passwordError: 'Password is invalid',
      },
    },
    totpForm: {
      title: 'Configure your TOTP',
      subtitle: 'Scan the QR code with your prefered application',
      label: 'Enter the code generated by your application',
      button: 'Verify',
      validation: {
        totp: 'A valid TOTP is required',
        totpLength: 'TOTP token should have 8 digits',
        totpInvalid: 'The provided code is invalid',
      },
    },
  },
};
