export default {
  security: {
    title: 'Security Settings',
    subtitle: 'Manage your account security and authentication.',
    email: 'Email',
    emailSubtitle: 'You will be log out and asked to verify your new address',
    changeEmailButton: 'Change Email',
    password: 'Password',
    lastChanged: 'Last changed {timeSince}',
    neverChanged: 'Never updated',
    changePasswordButton: 'Change Password',
    totp: 'Two-Factor Authentication',
    totpSubtitle: 'Add an extra layer of security to your account',
    totpEnabled: 'Enabled',
    totpDisabled: 'Disabled',
    totpConfigureButton: 'Configure',
    passwordVerifyForm: {
      title: 'Verify your password',
      subtitle: 'Confirm password to setup 2FA',
      label: 'Password',
      button: 'Verify',
      validation: {
        passwordError: 'Password is invalid',
      },
    },
    totpForm: {
      title: 'Configure your TOTP',
      subtitle: 'Scan the QR code with your prefered application',
      label: 'Enter the code generated by your application',
      button: 'Verify',
      validation: {
        totp: 'A valid TOTP is required',
        totpLength: 'TOTP token should have 8 digits',
        totpInvalid: 'The provided code is invalid',
      },
    },
    totpRecovery: {
      title: 'Save your recovery codes',
      subtitle:
        'These codes can be used to access your account if you lose your authenticator device',
      warning: {
        title: 'Important!',
        description:
          'Store these codes in a safe place. You will not be able to see them again.',
      },
      copy: 'Copy codes',
      copied: 'Copied!',
      download: 'Download codes',
      downloading: 'Downloading recovery codes...',
      downloadSuccess: 'Recovery codes downloaded successfully',
      downloadError: 'Failed to download, codes copied to clipboard instead',
      complete: 'I have saved my codes',
    },
    totpRegenerate: {
      button: 'Regenerate codes',
      title: 'Regenerate recovery codes',
      subtitle: 'Generate new recovery codes and invalidate the old ones',
      success: 'Recovery codes regenerated successfully',
      confirm: 'Regenerate codes',
      processing: 'Regenerating recovery codes...',
      passwordVerify: {
        title: 'Security Confirmation Required',
        description:
          'Please verify your password to regenerate recovery codes. This is a sensitive security operation.',
      },
      warning: {
        title: 'Warning!',
        description:
          'This will invalidate all your current recovery codes. Make sure you have access to your authenticator app.',
      },
      newCodes: {
        title: 'Your new recovery codes',
        subtitle: 'Your old recovery codes are no longer valid',
        warning:
          'These NEW codes replace your previous ones. Store them safely - you will not see them again.',
        complete: 'I have saved my new codes',
      },
      error: {
        title: 'Error',
        description: 'Failed to regenerate recovery codes',
      },
    },
    totpDisable: {
      button: 'Disable',
      title: 'Disable Two-Factor Authentication',
      subtitle: 'Turn off TOTP authentication for your account',
      success: 'Two-factor authentication disabled successfully',
      confirm: 'Disable TOTP',
      processing: 'Disabling two-factor authentication...',
      passwordVerify: {
        title: 'Security Confirmation Required',
        description:
          'Please verify your password to disable two-factor authentication. This will reduce your account security.',
      },
      warning: {
        title: 'Security Warning!',
        description:
          'Disabling 2FA will make your account less secure. Are you sure you want to continue?',
      },
      consequences: {
        title: 'This will:',
        item1: 'Remove TOTP requirement for login',
        item2: 'Invalidate all recovery codes',
        item3: 'Reduce your account security',
      },
      error: {
        title: 'Error',
        description: 'Failed to disable two-factor authentication',
      },
    },
    changeEmail: {
      title: 'Change Email',
      subtitle: 'Update your account email',
      passwordVerify: {
        title: 'Security Confirmation Required',
        description:
          'Please verify your password to update your email. This is a sensitive security operation.',
      },
    },
    changePassword: {
      title: 'Change Password',
      subtitle: 'Update your account password',
      currentPasswordLabel: 'Current Password',
      newPasswordLabel: 'New Password',
      confirmPasswordLabel: 'Confirm New Password',
      success: 'Password changed successfully',
      error: 'Failed to change password',
      logoutNotice:
        'For security reasons, you will be logged out to use your new password',
    },
  },
  profile: {
    title: 'Personal Information',
    subtitle: 'Update your personal details and profile information.',
    form: {
      displayName: 'Display Name',
      displayNamePlaceholder: 'How others will see you',
      firstName: 'First Name',
      lastName: 'Last Name',
      phoneNumber: 'Phone Number',
      jobTitle: 'Job Title',
      emailSubtitle: 'Update',
      validation: {
        firstName: 'First name must be valid',
        lastName: 'Last name must be valid',
        jobTitle: 'Job title must be valid',
        phoneNumber: 'Phone number must be valid',
        username: 'Display name must be valid',
      },
    },
  },
  common: {
    cancel: 'Cancel',
    retry: 'Try Again',
    saveChanges: 'Save Changes',
  },
  accountType: {
    enterprise: 'Enterprise',
  },
  settings: {
    title: 'Account Settings',
    subtitle: 'Manage your account preferences.',
    status: {
      title: 'Account Status',
      activeSubtitle: 'Your account is currently active',
      disabledSubtitle: 'Your account is currently deactivated',
      active: 'Active',
      disabled: 'Deactivated',
    },
  },
  dangerZone: {
    title: 'Danger Zone',
    subtitle: 'Irreversible and destructive actions',
    deleteAccount: {
      label: 'Delete Account',
      description:
        'Permanently delete your account and all associated data. This action cannot be undone.',
      button: 'Delete Account',
      title: 'Delete Your Account',
      subtitle: 'Permanently remove your account and all data',
      success: 'Your account has been scheduled for deletion',
      processing: 'Deleting your account...',
      confirm: 'Delete My Account',
      passwordVerify: {
        title: 'Security Confirmation Required',
        description:
          'Please verify your password to delete your account. This is a highly sensitive security operation.',
      },
      warning: {
        title: 'Warning: This Action Cannot Be Undone!',
        description:
          'You are about to permanently delete your account. All your data will be lost.',
      },
      consequences: {
        title: 'This will:',
        item1: 'Permanently delete all your personal data',
        item2: 'Remove all your projects and files',
        item3: 'Cancel any active subscriptions',
      },
      delay: {
        title: 'Deletion Process',
        description:
          'Your account will be marked for deletion and permanently removed after 30 days. During this period, you can contact us at support@example.com to cancel the deletion. A confirmation email will be sent to you.',
      },
      error: {
        title: 'Error',
        description: 'Failed to delete your account',
      },
    },
  },
};
